import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import clsx from "clsx";
import "dayjs/locale/zh-tw";
import dayjs from "dayjs";

import Header from "./_layout/header";
import Footer from "./_layout/footer";

dayjs.locale("zh-tw");

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "泰安觀止",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { lang: string };
}

export default function RootLayout({
  params: { lang },
  children,
}: RootLayoutProps) {
  return (
    <html lang="en" className="overscroll-none">
      <body
        className={clsx(
          inter.className,
          "flex",
          "flex-col",
          "items-stretch",
          "bg-black",
          "text-white",
          "bg-[url(/assets/background-image.gif)]",
          "bg-left",
          "bg-repeat"
        )}
      >
        <div
          className={clsx(
            "fixed",
            "-top-[10px]",
            "left-0",
            "w-full",
            "h-[600px]",
            "bg-top",
            "bg-repeat-x",
            'bg-[url("/assets/background-linear.png")]'
          )}
        />
        <div className="relative mx-auto w-full lg:w-[980px] flex flex-col max-[980px]:pt-[60px] min-h-[100dvh]">
          <Header />
          <div className="flex-auto">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
